blog/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('blogs.urls','blogs'), namespace='blogs')),
    path('users/', include(('users.urls','users'), namespace = 'users')),
]

blogs/urls.py
"""定义blogs的URL模式"""

from django.conf.urls import url

from . import views

urlpatterns = [
    # 主页
    url(r'^$', views.index, name='index'),
    
    # 显示所有博客
    url(r'^blogs/$', views.blogs, name = 'blogs'), 
    
    # 显示博客详细
    url(r'^blogs/(?P<blog_id>\d+)/$', views.blog, name = 'blog'),
    
    # 发布新博客
    url(r'^new_blog/$', views.new_blog, name = 'new_blog' ),
    
    # 用于编辑现有博客内容
    url(r'^edit_blog/(?P<blog_id>\d+)/$',views.edit_blog, 
      name = 'edit_blog'),
]

users/urls.py
"""为应用程序users定义URL模式"""

from django.conf.urls import url
from django.contrib.auth.views import login,logout

from . import views

urlpatterns = [
    # 登录页面
    url('^login/$', login, {'template_name': 'users/login.html'},
        name = 'login'),
    # 注销
    url('^logout/$', logout, {'template_name': 'users/logout.html'}, 
        name = 'logout'),
    # 登录页面
    url('^register/$', views.register, name='register'),
]

blogs/models.py
from django.db import models
from django.contrib.auth.models import User
#from django.forms.models import model_to_dict
# Create your models here.

class BlogPost(models.Model):
    """博客主题，内容发布"""
    title = models.CharField(max_length=200)
    text = models.TextField()
    # blogs_cont = {'title': title, 'text': text }
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User,on_delete=models.CASCADE)
    
    def __str__(self):
        """返回博客主题及文本"""
        return self.title
    
    
    

users/models.py
from django.db import models

# Create your models here.

blogs/forms.py
from django import forms

from .models import BlogPost

class NewBlogForm(forms.ModelForm):
    """发布新博客表单"""
    class Meta:
        model = BlogPost
        fields = ['title', 'text']
        labels = {'title': '', 'text': ''}

class EditBlogForm(forms.ModelForm):
    """编辑现有博客表单"""
    class Meta:
        model = BlogPost
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 100})}


        

blogs/views.py
from django.shortcuts import render
from .models import BlogPost
from .forms import NewBlogForm, EditBlogForm
from .check_owner import check_blog_owner
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
# Create your views here.
def index(request):
    """博客系统的主页"""
    return render(request, 'blogs/index.html')

def blogs(request):
    """显示所有博客"""
    blogs = BlogPost.objects.order_by('date_added')
    context = {'blogs': blogs}
    return render(request, 'blogs/blogs.html', context)

def blog(request, blog_id):
    """显示单个博客的内容"""
    blog = BlogPost.objects.get(id=blog_id)
    context = {'blog': blog, 'text': blog.text}
    return render(request, 'blogs/blog.html', context)

@login_required
def new_blog(request):
    """添加新blog"""
    if request.method != 'POST':
        # 未提交数据，创建一个新表单
        form = NewBlogForm()
    else:
        # 对提交的数据进行处理
        form = NewBlogForm(request.POST)
        if form.is_valid():
            new_blog = form.save(commit=False)
            new_blog.owner = request.user
            new_blog.save()
            form.save()
            return HttpResponseRedirect(reverse('blogs:blogs'))
    context = {'form': form}
    return render(request, 'blogs/new_blog.html',context)

@login_required
def edit_blog(request,blog_id):
    """在特定的blog中进行编辑"""
    blog = BlogPost.objects.get(id=blog_id)
    title = blog.title
    check_blog_owner(request, blog)
    if request.method != 'POST':
        # 未提交数据，创建一个空表单
        form = EditBlogForm(instance=blog)
    else:
        # 对提交的数据进行处理
        form = EditBlogForm(instance=blog, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('blogs:blog', 
                   args = [blog.id]))
    context = {'blog': blog, 'form': form}
    return render(request, 'blogs/edit_blog.html', context)
    

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login,logout,authenticate
from django.contrib.auth.forms import UserCreationForm
# Create your views here.

def register(request):
    """注册新用户"""
    if request.method != 'POST':
        # 显示空的注册表单
        form = UserCreationForm()
    else:
        # 处理填写好的表单
        form = UserCreationForm(data=request.POST)
        
        if form.is_valid():
            new_user = form.save()
            # 让用户自动登录，再重定向到主页
            authenticated_user = authenticate(username=new_user.username,
               password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('blogs:index'))
    context = {'form': form}
    return render(request, 'users/register.html', context)
    

blogs/templates/blogs/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    
    <title>Blogs</title>
    
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    
  </head>

  <body>
  <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed"
            data-toggle="collapse" data-target="#navbar"
            aria-expanded="false" aria-controls="navbar">
          </button>
          <a class="navbar-brand" href="{% url 'blogs:index' %}">
              Blog
          </a>
        </div>
        
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'blogs:blogs' %}">List</a></li>
          </ul>
          
          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
              <li><a>Hello, {{ user.username }}.</a></li>
              <li><a href="{% url 'users:logout' %}">log out</a></li>
            {% else %}
              <li><a href="{% url 'users:register' %}">register</a></li>
              <li><a href="{% url 'users:login' %}">log in</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    
    <div class="container">
      <div class="page-header">
        {% block header %}{% endblock header %}
      </div>
      
      <div>
        {% block content %}{% endblock content %}
      </div>
    
    </div> <!-- /container -->
  
  </body>


</html>

blogs/templates/blogs/blog.html
{% extends 'blogs/base.html' %}

{% block header %}
  <h2>{{ blog }}</h2>
{% endblock header %}


{% block content %}
  <blockquote>{{ blog.text }}</blockquote>
  {% if blog.owner == request.user %}
    <p><a href="{% url 'blogs:edit_blog' blog.id %}">edit blog</a></p>
  {% endif %}
{% endblock content %}

blogs/templates/blogs/blogs.html
{% extends "blogs/base.html" %}

{% block header %}
  <h2>Blogs</h2>
{% endblock header %}

{% block content %}
  
  <ul>
    {% for blog in blogs %}
      <li>
        <h3>
          <a href="{% url 'blogs:blog' blog.id %}">{{ blog.title }}</a>
        </h3>
      </li>
      {% empty %} 
        <li>No Blogs have been added yet.</li>
    {% endfor %}
  </ul>
  
  <h3><a href="{% url 'blogs:new_blog' %}">Add a new blog:</a></h3>

{% endblock content %}

blogs/templates/blogs/edit_blog.html
{% extends "blogs/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2><a href="{% url 'blogs:blog' blog.id %}">{{ blog }}</a></h2>
{% endblock header %}

{% block content %}
  <p>Edit Blog:</p>
  
  <form action="{% url 'blogs:edit_blog' blog.id %}" method = 'post' class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button name="submit" class="btn btn-primary">save changes</button>
    {% endbuttons %}
  </form>
  
{% endblock content %}

blogs/templates/blogs/index.html
{% extends "blogs/base.html" %}

{% block header %}
  <div class='jumbotron'>
    <h1>Share your views about the world, 
    keep the record of the process.</h1>
  </div>
{% endblock header %}

{% block content %}
  <h2>
    <a href="{% url 'users:register' %}">Register an account</a> to make
    your own blog, and list the blogs you're interested in.
  </h2>
{% endblock content %}

blogs/templates/blogs/new_blog.html
{% extends "blogs/base.html" %}
{% load bootstrap3 %}

{% block header %}
<h2>Add a new blog</h2>
{% endblock header %}

{% block content %}
  
  <form action="{% url 'blogs:new_blog' %}" method='post' class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %} 
      <button name = "submit" class="btn btn-primary">add blog</button>
    {% endbuttons %}
  </form>

{% endblock content %}
 

users/templates/users/login.html
{% extends "blogs/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>Log in to your account.</h2>
{% endblock header %}

{% block content %}
  
  <form method="post" action = "{% url 'users:login' %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    
    {% buttons %}
      <button name="submit" class="btn btn-primary">log in</button>
    {% endbuttons %}
    
     <input type="hidden" name="next" value="{% url 'blogs:index' %}" />
  </form>
  
{% endblock content %}

users/templates/users/logout.html
{% extends "blogs/base.html" %}

{% block content %}
<!--
<form method="post" action="{% url 'users:logout' %}">
  <input type="hidden" name="next" value="{% url 'blogs:index' %}" />
</form>
-->
{% endblock content %}

users/templates/users/register.html
{% extends "blogs/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>Register</h2>
{% endblock header %}

{% block content %}

    <form method="post" action="{% url 'users:register' %}", class="form">
      
      {% csrf_token %}
      {% bootstrap_form form %}
    
      {% buttons %}
        <button name="submit" class="btn btn-primary">register</button>
      {% endbuttons %}
      
      <input type="hidden" name="next" value="{% url 'blogs:index' %}" />
    </form>
    
{% endblock content %}